require "core.options"
require "core.packer"
require "core.keymaps"
require "core.autocommands"
require "core.impatient"
require "core.notify"
require "core.theme.colorscheme"
require "core.theme.cmp"
require "core.theme.evilline"
-- require "core.theme.vscodeline"
